language: android
android:
  components:
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk8

notifications:
  email: false
