language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk8

notifications:
  email: false
